git:
  depth: 1
dist: xenial
sudo: true
language: python
cache:
  pip: true
matrix:
  include:
  - python: "3.4"
    env: IPYTHON_VERSION='==4.1.0'
  - python: "3.7"
    env: IPYTHON_VERSION=
install: |
  pip install --upgrade pip setuptools
  pip install --upgrade pytest pytest-cov codecov ipython"$IPYTHON_VERSION" .
script: pytest --cov
after_success: codecov
