jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python34:
        python.version: '3.4'
      Python37:
        python.version: '3.7'

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - bash: |
      python -mpip install --upgrade pytest pytest-cov
      case "$PYTHON_VERSION" in
      3.4)
        pip install ipython==4.1.0;;
      3.7)
        ;;
      *)
        exit 1;;
      esac
      pip install .
    displayName: 'Install'

  - bash: |
      python -mpytest --junitxml=junit/test-results.xml \
        --cov --cov-report=xml --cov-report=html
    displayName: 'Test'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version) / Linux'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
